-- MySQL Script generated by MySQL Workbench
-- Wed Feb  7 18:11:08 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema BD-BELA
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema BD-BELA
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BD-BELA` DEFAULT CHARACTER SET utf8 ;
USE `BD-BELA` ;

-- -----------------------------------------------------
-- Table `BD-BELA`.`Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD-BELA`.`Persona` (
  `idPersona` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(30) NOT NULL,
  `apellido1` VARCHAR(30) NOT NULL,
  `apellido2` VARCHAR(30) NOT NULL,
  `correo` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`idPersona`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD-BELA`.`Rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD-BELA`.`Rol` (
  `idRol` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idRol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD-BELA`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD-BELA`.`Usuario` (
  `idUsuario` INT NOT NULL,
  `idRol` INT NOT NULL,
  `usuario` VARCHAR(45) NOT NULL,
  `contrasena` VARCHAR(45) NOT NULL,
  INDEX `FK_IDROL_idx` (`idRol` ASC),
  INDEX `FK_IDUSUARIO_idx` (`idUsuario` ASC),
  CONSTRAINT `FK_IDROL`
    FOREIGN KEY (`idRol`)
    REFERENCES `BD-BELA`.`Rol` (`idRol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_IDUSUARIO`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `BD-BELA`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD-BELA`.`Materia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD-BELA`.`Materia` (
  `idMateria` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`idMateria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD-BELA`.`DetalleMateria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD-BELA`.`DetalleMateria` (
  `idDetalleMateria` INT NOT NULL AUTO_INCREMENT,
  `idMateria` INT NOT NULL,
  `idUsuario` INT NOT NULL,
  `grado` INT NOT NULL,
  PRIMARY KEY (`idDetalleMateria`),
  INDEX `FK_IDMATERIA_idx` (`idMateria` ASC),
  INDEX `FK_IDUSUARO_idx` (`idUsuario` ASC),
  CONSTRAINT `FK_IDMATERIA`
    FOREIGN KEY (`idMateria`)
    REFERENCES `BD-BELA`.`Materia` (`idMateria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_IDUSUARO`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `BD-BELA`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD-BELA`.`TipoNoticia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD-BELA`.`TipoNoticia` (
  `idTipoNoticia` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTipoNoticia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD-BELA`.`Noticia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD-BELA`.`Noticia` (
  `idNoticia` INT NOT NULL AUTO_INCREMENT,
  `idUsuario` INT NOT NULL,
  `idTipo` INT NOT NULL,
  `titulo` VARCHAR(100) NOT NULL,
  `descripcion` VARCHAR(300) NULL,
  `contenido` VARCHAR(1000) NULL,
  `imagen` VARCHAR(45) NULL,
  `fechaHora` DATETIME NOT NULL,
  PRIMARY KEY (`idNoticia`),
  INDEX `FK_IDUSUARIONOTI_idx` (`idUsuario` ASC),
  INDEX `FK_TIPONOTI_idx` (`idTipo` ASC),
  CONSTRAINT `FK_IDUSUARIONOTI`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `BD-BELA`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_TIPONOTI`
    FOREIGN KEY (`idTipo`)
    REFERENCES `BD-BELA`.`TipoNoticia` (`idTipoNoticia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD-BELA`.`MasImagen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD-BELA`.`MasImagen` (
  `idImagenNoticia` INT NOT NULL AUTO_INCREMENT,
  `idNoticia` INT NOT NULL,
  `imagen` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idImagenNoticia`),
  INDEX `FK_IDNOTICIAIMA_idx` (`idNoticia` ASC),
  CONSTRAINT `FK_IDNOTICIAIMA`
    FOREIGN KEY (`idNoticia`)
    REFERENCES `BD-BELA`.`Noticia` (`idNoticia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD-BELA`.`Material`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD-BELA`.`Material` (
  `idMaterial` INT NOT NULL AUTO_INCREMENT,
  `idDetalleMateria` INT NOT NULL,
  `titulo` VARCHAR(100) NOT NULL,
  `mensaje` VARCHAR(300) NOT NULL,
  `material` VARCHAR(45) NOT NULL,
  `fechaHora` DATETIME NOT NULL,
  PRIMARY KEY (`idMaterial`),
  INDEX `FK_IDDETALLEMATERIA_idx` (`idDetalleMateria` ASC),
  CONSTRAINT `FK_IDDETALLEMATERIA`
    FOREIGN KEY (`idDetalleMateria`)
    REFERENCES `BD-BELA`.`DetalleMateria` (`idDetalleMateria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD-BELA`.`MasMaterial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD-BELA`.`MasMaterial` (
  `idmasMaterial` INT NOT NULL AUTO_INCREMENT,
  `idMateria` INT NOT NULL,
  `material` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idmasMaterial`),
  INDEX `FK_IDMATERIAL_idx` (`idMateria` ASC),
  CONSTRAINT `FK_IDMATERIAL`
    FOREIGN KEY (`idMateria`)
    REFERENCES `BD-BELA`.`Material` (`idMaterial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD-BELA`.`MensajeContacto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD-BELA`.`MensajeContacto` (
  `idMensaje` INT NOT NULL AUTO_INCREMENT,
  `correo` VARCHAR(60) NOT NULL,
  `asunto` VARCHAR(60) NOT NULL,
  `mensaje` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`idMensaje`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
